export const MESSAGE_TYPES = Object.freeze({
  GET_NEXT_MATCH: "GET_NEXT_MATCH",
  RESCHEDULE: "RESCHEDULE",
  CREATE_TEST_MATCH: "CREATE_TEST_MATCH",
  CLEAR_TEST_MATCHES: "CLEAR_TEST_MATCHES",
  SHOW_DIRECT_NOTIFICATION: "SHOW_DIRECT_NOTIFICATION"
});
